### PR TITLE
Do not accept it, not working!

### PR DESCRIPTION
**Pull request by aleixjf**
This is for you to be able to check the things I've implemented so far... mainly the UI... and I've added how the query should be sent on the iTunes.rs file too. Hope it's useful

### CODE REVIEW

**Comment by Marekkon5** [comment]
Hi, thanks for the PR, however I will probably have to entirely rewrite it, because:
a) My Discogs API implementation isn't really clean (sorry for that, will have to clean as well),
b) Discogs doesn't search by tracks, but by albums (releases/masters), while iTunes does. So it makes way more sense to base the implementation on for example Beatport one.
c) Again - iTunes doesn't have release/master system, nor styles - so it doesn't make sense basing it on Discogs.

Still thanks for the base implementations, will use them as references, however it will probably take me some time to implement it all.

**Comment by aleixjf** [comment]
Yeag, that's what I thought while I was checking the code. However, the Beatport integration doesn't offer a request/minute limit + it scraps through the website rather than connecting through it's API, so that's why I used the Discogs one. Probably tomorrow/tuesday I'll give it another look and see what I can do! 😇

**Comment by Marekkon5** [comment]
I've just pushed my initial implementation of iTunes, lemme know if it works for you. I also noticed there isn't much tags available, so lemme know if there is a way to get more. Thanks

**Comment by aleixjf** [comment]
Thanks! I was working on it myself today! I'll review it and see what can be added/enhaced! :)

The way to get more tags, by the way, is using the Apple Music API, not the iTunes Search API. I'll do some research and let you know :)

**Comment by Marekkon5** [comment]
Thanks, just lemme know by replying here.

**Pull request closed without merging**
